#This C.oudFormation template will create RDS  for i6 Application in AWS lower environment. 
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  Environment:
    Type: String
    Description: Environment Name (DEV/QA/UAT)
    AllowedValues: ['DEV', 'QA', 'UAT']
  Database:
    Type: String
    Default: 'I6'
  AppID:
    Type: String
    Default: 'EFCACDEA-1B23-5D54-6329-11B7B04BCBE2'
    Description: AppID
  BU:
    Type: String
    Default: 'DJI'
    Description: BU Name
  SupportGroup:
    Type: String
    Default: 'IM-SPDJI-Index infrastructure'
    Description: SupportGroup Name
  DBUsername:
    NoEcho: 'true'
    Description: i6 RDS DB Master username
    Type: String
    Default: 'rdsmstr'
    MinLength: '3'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters
  DBPassword:
    NoEcho: 'true'
    Description: Password of RDS database access
    Type: String
    MinLength: '8'
    MaxLength: '16'
    AllowedPattern: '^[a-zA-Z]+[0-9a-zA-Z_]*$'
    ConstraintDescription: Must start with a letter. Only numbers, letters, and _ accepted. max length 16 characters
  AllowMajorVersionUpgrade:
    Description: If you update the EngineVersion property to a version that is different from the DB instances current major version, set this property to true
    Type: String
    AllowedValues: [true, false]
    ConstraintDescription: "Value must be boolean value."
    Default: false
  AutoMinorVersionUpgrade:  
    Description: Indicates that minor engine upgrades are applied automatically to the DB instance during the maintenance window. The default value is true.
    Type: String
    AllowedValues: [true, false]
    Default: true
    ConstraintDescription: "Value must be boolean value."  
  BackupRetentionPeriod:
    Description: The number of days during which automatic DB snapshots are retained.
    Type: String
    AllowedPattern: "^[0-9]{1,3}$"
    ConstraintDescription: "Value must be a valid number between 0-999."
    Default: 3
  DBInstanceClass:
    Description: The name of the compute and memory capacity classes of the DB instance.
    Type: String
    Default: db.r5.2xlarge
    AllowedValues: [db.r5.large,db.r5.xlarge,db.r5.2xlarge] 
  Engine:
    Description: The name of the database engine to be used for this instance.
    Type: String
    Default: aurora-postgresql
    AllowedValues: [mysql, mariadb, postgres, oracle-ee,aurora-postgresql]
    ConstraintDescription: "Please specify either a mysql, mariadb, or postgres engine for the RDS instance."
  DeletionProtection:
    Description: A value that indicates whether the DB cluster has deletion protection enabled. The database can be deleted when deletion protection is enabled. By default, deletion protection is disabled.
    Type: String
    Default: yes
  EngineVersion:
    Description: The version number of the database engine to use.
    Type: String
    Default: 13.4
  DBCACertificateIdentifier:
    Description: The name of the CA Certificate to use with the DB instance.
    Type: String
    Default: rds-ca-rsa2048-g1
    AllowedValues: [rds-ca-rsa2048-g1,rds-ca-rsa4096-g1,rds-ca-ecc384-g1,rds-ca-2019]
  PreferredMaintenanceWindow:
    Description: Maintenance Window.
    Type: String
    #Default: fri:03:00-fri:04:00
    Default: sat:04:01-sat:08:00
  PreferredBackupWindow:
    Description: Backup Window.
    Type: String
    #Default: fri:03:00-fri:04:00
    Default: 03:01-04:00   
  DBClusterIdentifier:
    Description: A name of the DB cluster.
    Type: String
  DBInstanceIdentifier:
    Description: A name of the DB instance.
    Type: String  

Mappings:
  DBSubnetGroup:
    DEV:
      DBSubnetGroupName: dev-rds-new-private-subnet-group
    QA:
      DBSubnetGroupName: qa-rds-new-private-subnet-group
    UAT:
      DBSubnetGroupName: uat-rds-new-private-subnet-group
  VPCSecurityGroups:
    DEV:
      SGID: [sg-03dec67f]
    QA:
      SGID: [sg-a5da35d4]
  KeyNames:
    DEV:
      Name: 'alias/rds-nonprod-kms-key' 
    QA:
      Name: 'alias/QA-RDS' 
  DBParameterGroupName:
    DEV: 
      Name: dev-i6-param-aurapostgres13
    QA:
      Name: qa-i6-param-aurapostgres13
  DBClusterParameterGroup:
    DEV:
      Name: dev-i6-cluster-param-aurapostgres13
    QA:
      Name: qa-i6-cluster-param-aurapostgres13
  DBName:
    DEV:
      Name: i6d
    QA:
      Name: i6q

Resources:
  i6RDSCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      DBClusterIdentifier: !Ref DBClusterIdentifier
      Engine: !Ref Engine
      EngineVersion: !Ref EngineVersion
      Port: 5432
      DBSubnetGroupName: !FindInMap
        - DBSubnetGroup
        - !Ref Environment
        - DBSubnetGroupName
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      BackupRetentionPeriod: !Ref BackupRetentionPeriod
      EnableIAMDatabaseAuthentication: Yes
      PreferredMaintenanceWindow: !Ref PreferredMaintenanceWindow
      PreferredBackupWindow: !Ref PreferredBackupWindow
      DBClusterParameterGroupName: !FindInMap
        - DBClusterParameterGroup
        - !Ref Environment
        - Name
      DeletionProtection: !Ref DeletionProtection
      VpcSecurityGroupIds: !FindInMap
        - VPCSecurityGroups
        - !Ref Environment
        - SGID
      StorageEncrypted: Yes
      KmsKeyId: !FindInMap
        - KeyNames
        - !Ref Environment
        - Name
      EnableCloudwatchLogsExports:
        - 'postgresql'
      DatabaseName: !FindInMap
        - DBName
        - !Ref Environment
        - Name

  i6RDSInstance1: 
    Type: 'AWS::RDS::DBInstance'
    Properties: 
      DBClusterIdentifier: !Ref i6RDSCluster
      DBInstanceClass: !Ref DBInstanceClass
      CACertificateIdentifier: !Ref DBCACertificateIdentifier
      DBParameterGroupName: !FindInMap
        - DBParameterGroupName
        - !Ref Environment
        - Name
      CopyTagsToSnapshot: Yes
      PubliclyAccessible: No
      DBInstanceIdentifier: !Ref DBInstanceIdentifier
      Engine: !Ref Engine
      EngineVersion: !Ref EngineVersion
      PubliclyAccessible: No
      
      Tags:
      - Key: Name
        Value: !Sub ${Environment}-${Database}-${DBInstanceIdentifier}-01
      - Key: Owner
        Value: !Ref Database
      - Key: AppID
        Value: !Ref AppID
      - Key: BU
        Value: !Ref BU
      - Key: Environment
        Value: !Ref Environment
      - Key: SupportGroup
        Value: !Ref SupportGroup
      - Key: UsedFor
        Value: RDS
      - Key: AutomatedSnapshot
        Value: Yes 

Outputs:
  ClusterEndpoint:
    Description: 'Aurora Cluster/Writer Endpoint'
    Value: !GetAtt 'i6RDSCluster.Endpoint.Address'
  ReaderEndpoint:
    Description: 'Aurora Reader Endpoint'
    Value: !GetAtt 'i6RDSCluster.ReadEndpoint.Address'
