#This CFT will deploy RDS DB for VAULT in AWS lower environment. 
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  Environment:
    Type: String
    Description: Environment Name (DEV/QA/UAT)
    AllowedValues: ['DEV', 'QA', 'UAT', 'dev', 'qa','uat']
  Database:
    Type: String
    Default: 'INFRA'
    Description: Database Name  
  Owner:
    Type: String
    Default: 'INFRA'
    Description: Owner Name  
  AppID:
    Type: String
    Default: 'EEA3AA80-35D5-4C84-8403-39761A7215B8' 
    Description: AppID
  BU: 
    Type: String
    Default: 'DJI'
    Description: BU Name 
  SupportGroup:
    Type: String
    Default: 'IM-SPDJI-Index infrastructure'
    Description: SupportGroup Name
  DBUsername:
    NoEcho: 'true'
    Description: Username for Oracle database access
    Type: String
    Default: 'rdsmstr'
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DBPassword:
    NoEcho: 'true'
    Description: Password Oracle database access
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '^[a-zA-Z]+[0-9a-zA-Z_]*$'
    ConstraintDescription: Must start with a letter. Only numbers, letters, and _ accepted. max length 16 characters
  #DBAllocatedStorage:
  #  Default: '1000'
  #  Description: The size of the database (GiB)
  #  Type: Number
  #  MinValue: '1000'
  #  MaxValue: '2000'
  #  ConstraintDescription: must be between 20 and 65536 GiB. 
  AllowMajorVersionUpgrade:
    Description: If you update the EngineVersion property to a version that is different from the DB instances current major version, set this property to true.
    Type: String
    AllowedValues: [true, false]
    ConstraintDescription: "Value must be boolean value."
    Default: false
  AutoMinorVersionUpgrade:
    Description: Indicates that minor engine upgrades are applied automatically to the DB instance during the maintenance window. The default value is true.
    Type: String
    AllowedValues: [true, false]
    Default: true
    ConstraintDescription: "Value must be boolean value."
  BackupRetentionPeriod:
   Description: The number of days during which automatic DB snapshots are retained.
   Type: String
   AllowedPattern: "^[0-9]{1,3}$"
   ConstraintDescription: "Value must be a valid number between 0-999."
   Default: 3
  DBInstanceClass:
    Description: The name of the compute and memory capacity classes of the DB instance.
    Type: String
    Default: db.r5.large
    AllowedValues: [db.m5.large,db.m5.xlarge,db.m5.2xlarge,db.m5.4xlarge,db.m5.8xlarge,db.m5.12xlarge,db.m5.16xlarge,db.m5.24xlarge,db.r5.2xlarge,db.r5.large] 
    
  Engine:
    Description: The name of the database engine to be used for this instance.
    Type: String
    Default: oracle-ee
    AllowedValues: [mysql, mariadb, postgres,oracle-ee]
    ConstraintDescription: "Please specify either a mysql, mariadb, or postgres engine for the RDS instance."
  #MultiAZ:
  #  Description: Specifies if the database instance is a multiple Availability Zone deployment.
  #  Type: String
  #  AllowedValues: [true, false]
  #  Default: false
  #  ConstraintDescription: "Value must be boolean value."  
  DeletionProtection:
    Description: A value that indicates whether the DB cluster has deletion protection enabled. The database can be deleted when deletion protection is enabled. By default, deletion protection is disabled.
    Type: String
    Default: yes
  PreferredBackupWindow:
    Description: Backup Window.
    Type: String
    Default: 03:00-04:00
  EngineVersion:
    Description: The version number of the database engine to use.
    Type: String
    Default: 19.0.0.0.ru-2021-10.rur-2021-10.r1
    AllowedValues: [19.0.0.0.ru-2021-01.rur-2021-01.r1,19.0.0.0.ru-2021-01.rur-2021-01.r2,19.0.0.0.ru-2021-10.rur-2021-10.r1]
  DBInstanceIdentifier:
    Description: A name for the DB instance.
    Type: String
  StorageType:
    Type: String
    Default: gp2
    AllowedValues: [gp2, io1]
  #MaxAllocatedStorage:
    #Type: String
    #Default: 1000
    #Description: The upper limit to which Amazon RDS can automatically scale the storage of the DB instance.  
  CharacterSetName:
    Type: String
    Default: AL32UTF8
    Description: For supported engines, indicates that the DB instance should be associated with the specified character set.


Mappings:
  DBSubnetGroup:
    DEV:
      DBSubnetGroupName: dev-usw2-pvt-subnet-group
    QA:
      DBSubnetGroupName: qa-usw2-pvt-subnet-group
    UAT:
      DBSubnetGroupName: uat-usw2-pvt-subnet-group
  VPCSecurityGroups:
    DEV:
      SGID: [sg-097154ba12c957de1]
    QA:
      SGID: [sg-0c1d6b5c4a44f764e]
    UAT:
      SGID: [sg-021d935484a5770b7]      ##SGID: [sg-8b5553fd] before
  KeyNames:
    DEV:
      Name: 'alias/usw2-rds' 
    QA:
      Name: 'alias/usw2-rds' 
    UAT:
      Name: 'alias/usw2-rds'
  DBParameterGroupName:
    DEV: 
      Name: dev-vault-param-oracle
    QA:
      Name: qa-vault-param-oracle
    UAT:
      Name: uat-vault-param-oracle
  OptionGroupName:
    DEV:
      Name: dev-vault-option-oracle
    QA:
      Name: qa-vault-option-oracle
    UAT:
      Name: uat-vault-option-oracle
  DBAllocatedStorage:
    DEV:
      Storage: 1000
    QA:
      Storage: 1000
    UAT:
      Storage: 1000
  DBName:
    DEV:
      Name: vaultd
    QA:
      Name: vaultq
    UAT:
      Name: vaultb
  MultiAZ:
    DEV:
      Name: false
    QA:
      Name: false
    UAT:
      Name: true
  PreferredMaintenanceWindow:
    DEV:
      Name: 'tue:04:01-tue:08:00' 
    QA:
      Name: 'wed:04:01-wed:08:00' 
    UAT:
      Name: 'thu:04:01-thu:08:00'
    
Resources:
  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: !FindInMap
        - DBAllocatedStorage
        - !Ref Environment
        - Storage
      AllowMajorVersionUpgrade: !Ref AllowMajorVersionUpgrade
      AutoMinorVersionUpgrade: !Ref AutoMinorVersionUpgrade
      BackupRetentionPeriod: !Ref BackupRetentionPeriod
      DBInstanceClass: !Ref DBInstanceClass
      DBName: !FindInMap
        - DBName
        - !Ref Environment
        - Name
      Engine: !Ref Engine
      EngineVersion: !Ref EngineVersion
      LicenseModel: bring-your-own-license
      DBSubnetGroupName: !FindInMap
        - DBSubnetGroup
        - !Ref Environment
        - DBSubnetGroupName
      VPCSecurityGroups: !FindInMap
        - VPCSecurityGroups
        - !Ref Environment
        - SGID
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      MultiAZ: !FindInMap
        - MultiAZ
        - !Ref Environment
        - Name
      PreferredBackupWindow: !Ref PreferredBackupWindow
      PreferredMaintenanceWindow: !FindInMap
        - PreferredMaintenanceWindow
        - !Ref Environment
        - Name
      StorageEncrypted: Yes
      DeletionProtection: !Ref DeletionProtection
      CopyTagsToSnapshot: Yes
      DeleteAutomatedBackups: Yes
      PubliclyAccessible: No
      StorageType: !Ref StorageType
      DBInstanceIdentifier: !Ref DBInstanceIdentifier
      KmsKeyId: !FindInMap
        - KeyNames
        - !Ref Environment
        - Name
      DBParameterGroupName: !FindInMap
        - DBParameterGroupName
        - !Ref Environment
        - Name
      OptionGroupName: !FindInMap
        - OptionGroupName
        - !Ref Environment
        - Name
      #MaxAllocatedStorage: !Ref MaxAllocatedStorage
      CharacterSetName: !Ref CharacterSetName
      EnableCloudwatchLogsExports:
        - 'audit'
        - 'listener'
        - 'alert'
        - 'trace'
      #EnablePerformanceInsights: !Ref EnablePerformanceInsights
      #PerformanceInsightsKMSKeyId: arn:aws:kms:us-east-1:699183880494:key/b0505725-3c0a-467a-8fdb-3d8f9ba574ad
      #PerformanceInsightsRetentionPeriod: !Ref PerformanceInsightsRetentionPeriod

      Tags:
      - Key: Name
        Value: !Sub ${Environment}-${Database}-${DBInstanceIdentifier}
      - Key: Owner
        Value: !Ref Owner
      - Key: AppID
        Value: !Ref AppID
      - Key: BU
        Value: !Ref BU
      - Key: Environment
        Value: !Ref Environment
      - Key: SupportGroup
        Value: !Ref SupportGroup
      - Key: UsedFor
        Value: RDS   
Outputs:
  EndPoint: 
    Description: 'EndPoint for RDS DB'
    Value: !GetAtt 'RDSInstance.Endpoint.Address'
  InstanceName:
    Description:  'InstanceName of the newly created RDS Instance'
    Value: !Ref 'RDSInstance' 
