#This CFT will deploy RDS DB for Kenstar using snapshot in AWS lower environment. 
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  Environment:
    Type: String
    Description: Environment Name (DEV/QA/UAT)
    AllowedValues: ['DEV', 'QA', 'dev', 'qa','UAT','uat']
  Database:
    Type: String
    Default: 'KENSTAR'
    Description: Database Name  
  AppID:
    Type: String
    Default: '403A115B-3E7F-4163-BE88-D67982C6B566' 
    Description: AppID
  BU: 
    Type: String
    Default: 'DJI'
    Description: BU Name 
  SupportGroup:
    Type: String
    Default: 'IM-SPDJI-Index infrastructure'
    Description: SupportGroup Name
  DBSnapshotIdentifier:
    Type: String
    Description:  ARN of the DB snapshot

  #DBName:
  #  Description: The name of the database inside the instance.
  #  Type: String
  #  Default: DEVKENSTAR
  #DBUsername:
  #  NoEcho: 'true'
  #  Description: Username for MySQL database access
  #  Type: String
  #  Default: 'rdsmstr'
  #  MinLength: '1'
  #  MaxLength: '16'
  #  AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
  #  ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  #DBPassword:
  #  NoEcho: 'true'
  #  Description: Password MySQL database access
  #  Type: String
  #  MinLength: '8'
  #  MaxLength: '41'
  #  AllowedPattern: '^[a-zA-Z]+[0-9a-zA-Z_]*$'
  #  ConstraintDescription: Must start with a letter. Only numbers, letters, and _ accepted. max length 16 characters
  #DBAllocatedStorage:
  #  Default: '300'
  #  Description: The size of the database (GiB)
  #  Type: Number
  #  MinValue: '500'
  #  MaxValue: '1000'
  #  ConstraintDescription: must be between 20 and 65536 GiB. 
  AllowMajorVersionUpgrade:
    Description: If you update the EngineVersion property to a version that is different from the DB instances current major version, set this property to true.
    Type: String
    AllowedValues: [true, false]
    ConstraintDescription: "Value must be boolean value."
    Default: false
  AutoMinorVersionUpgrade:
    Description: Indicates that minor engine upgrades are applied automatically to the DB instance during the maintenance window. The default value is true.
    Type: String
    AllowedValues: [true, false]
    Default: true
    ConstraintDescription: "Value must be boolean value."
  BackupRetentionPeriod:
   Description: The number of days during which automatic DB snapshots are retained.
   Type: String
   AllowedPattern: "^[0-9]{1,3}$"
   ConstraintDescription: "Value must be a valid number between 0-999."
   Default: 3
  # DBInstanceClass:
  #   Description: The name of the compute and memory capacity classes of the DB instance.
  #   Type: String
  #   Default: db.m5.2xlarge
  #   AllowedValues: [db.m5.large,db.m5.xlarge,db.m5.2xlarge,db.m5.4xlarge,db.m5.8xlarge,db.m5.12xlarge,db.m5.16xlarge,db.m5.24xlarge,db.r5.2xlarge] 
    
  Engine:
    Description: The name of the database engine to be used for this instance.
    Type: String
    Default: mysql
    AllowedValues: [mysql, mariadb, postgres,oracle-ee]
    ConstraintDescription: "Please specify either a mysql, mariadb, or postgres engine for the RDS instance."
  DBCACertificateIdentifier:
    Description: The name of the CA Certificate to use with the DB instance.
    Type: String
    Default: rds-ca-rsa2048-g1
    AllowedValues: [rds-ca-rsa2048-g1,rds-ca-rsa4096-g1,rds-ca-ecc384-g1,rds-ca-2019]
  MultiAZ:
    Description: Specifies if the database instance is a multiple Availability Zone deployment.
    Type: String
    AllowedValues: [true, false]
    Default: false
    ConstraintDescription: "Value must be boolean value."  
  PreferredMaintenanceWindow:
    Description: Maintenance Window.
    Type: String
    #Default: fri:03:00-fri:04:00
    Default: sat:04:01-sat:08:00
  DeletionProtection:
    Description: A value that indicates whether the DB cluster has deletion protection enabled. The database can be deleted when deletion protection is enabled. By default, deletion protection is disabled.
    Type: String
    Default: no
  PreferredBackupWindow:
    Description: Backup Window.
    Type: String
    Default: 03:01-04:00
  EngineVersion:
    Description: The version number of the database engine to use.
    Type: String
    Default: 8.0.28
    AllowedValues: [8.0.21,8.0.20,8.0.19,8.0.23,8.0.28]
  #VPCSecurityGroups:
  #  Description: Specify SG for Kenstar RDS
  #  Type: List<AWS::EC2::SecurityGroup::Id>
  #  ConstraintDescription: "Please provide valid ids for the security group(s)."
  #DBSubnetGroupName:
  #  Description: A DB subnet group to associate with the DB instance. 
  #  Type: String  
  DBInstanceIdentifier:
    Description: A name for the DB instance.
    Type: String
  #KmsKeyId:
  #  Description: KMS Key to use
  #  #Type: List<AWS::KMS::Key>
  #Type: String
  StorageType:
    Type: String
    Default: gp3
    AllowedValues: [gp3,io1]
  #DBParameterGroupName:
  #  Type: String

  #OptionGroupName:
  #  Type: String
  MaxAllocatedStorage:
    Type: String
    Default: 1000
    Description: The upper limit to which Amazon RDS can automatically scale the storage of the DB instance.  

Mappings:
  DBSubnetGroup:
    DEV:
      DBSubnetGroupName: dev-rds-new-private-subnet-group
    QA:
      DBSubnetGroupName: qa-rds-new-private-subnet-group
    UAT:
      DBSubnetGroupName: uat-rds-new-private-subnet-group

  VPCSecurityGroups:
    DEV:
      SGID: [sg-03dec67f]
    QA:
      SGID: [sg-a5da35d4]
    UAT:
      SGID: [sg-8b5553fd]  
  KeyNames:
    DEV:
      Name: 'alias/rds-nonprod-kms-key' 
    QA:
      Name: 'alias/QA-RDS' 
    UAT:
      Name: 'alias/UAT-RDS'
  DBParameterGroupName:
    DEV: 
      Name: dev-use1-kenstar-mysql-8-param-group
    QA:
      Name: qa-kenstar-param-mysql 
    UAT:
      Name: uat-kenstar-param-mysql 
  OptionGroupName:
    DEV:
      Name: dev-kenstar-option-mysql
    QA:
      Name: qa-kenstar-option-mysql
    UAT:
      Name: uat-kenstar-option-mysql
  
  DBAllocatedStorage:
    DEV:
      Storage: 1000
    QA:
      Storage: 500
    UAT:
      Storage: 500
  DBName:
    DEV:
      Name: devkenstar
      #Name: DEVKENSTAR
    QA:
      Name: qakenstar
      #Name: QAKENSTAR
    UAT:
      Name: uatkenstar
      #Name: UATKENSTAR
  DBInstanceClass:
    DEV:
      type: db.m5.xlarge
    QA:
      type: db.m5.2xlarge
    UAT:
      type: db.m5.xlarge    


Resources:
  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: !FindInMap
        - DBAllocatedStorage
        - !Ref Environment
        - Storage
      AllowMajorVersionUpgrade: !Ref AllowMajorVersionUpgrade
      AutoMinorVersionUpgrade: !Ref AutoMinorVersionUpgrade
      BackupRetentionPeriod: !Ref BackupRetentionPeriod
      DBInstanceClass: !FindInMap
        - DBInstanceClass
        - !Ref Environment
        - type
      DBSnapshotIdentifier: !Ref DBSnapshotIdentifier
      CACertificateIdentifier: !Ref DBCACertificateIdentifier
     #DBName: !FindInMap
     #   - DBName
     #   - !Ref Environment
     #   - Name
      Engine: !Ref Engine
      EngineVersion: !Ref EngineVersion
      Port: 3306
      DBSubnetGroupName: !FindInMap
        - DBSubnetGroup
        - !Ref Environment
        - DBSubnetGroupName
      VPCSecurityGroups: !FindInMap
        - VPCSecurityGroups
        - !Ref Environment
        - SGID

      #MasterUsername: !Ref DBUsername
      #MasterUserPassword: !Ref DBPassword
      PreferredMaintenanceWindow: !Ref PreferredMaintenanceWindow
      PreferredBackupWindow: !Ref PreferredBackupWindow
      MultiAZ: !Ref MultiAZ
      StorageEncrypted: Yes
      DeletionProtection: !Ref DeletionProtection
      CopyTagsToSnapshot: Yes
      DeleteAutomatedBackups: Yes
      PubliclyAccessible: No
      StorageType: !Ref StorageType
      Iops: 12000
      DBInstanceIdentifier: !Ref DBInstanceIdentifier
      #KmsKeyId: arn:aws:kms:us-east-1:699183880494:key/b0505725-3c0a-467a-8fdb-3d8f9ba574ad
      KmsKeyId: !FindInMap
        - KeyNames
        - !Ref Environment
        - Name
      DBParameterGroupName: !FindInMap
        - DBParameterGroupName
        - !Ref Environment
        - Name
      OptionGroupName: !FindInMap
        - OptionGroupName
        - !Ref Environment
        - Name
      MaxAllocatedStorage: !Ref MaxAllocatedStorage
      #EnablePerformanceInsights: !Ref EnablePerformanceInsights
      #PerformanceInsightsKMSKeyId: arn:aws:kms:us-east-1:699183880494:key/b0505725-3c0a-467a-8fdb-3d8f9ba574ad
      #PerformanceInsightsRetentionPeriod: !Ref PerformanceInsightsRetentionPeriod
      #CharacterSetName: !Ref CharacterSetName

    
    
  
      Tags:
      - Key: Name
        Value: !Sub ${Environment}-${Database}-${DBInstanceIdentifier}
      - Key: Owner
        Value: !Ref Database
      - Key: AppID
        Value: !Ref AppID
      - Key: BU
        Value: !Ref BU
      - Key: Environment
        Value: !Ref Environment
      - Key: SupportGroup
        Value: !Ref SupportGroup
      - Key: UsedFor
        Value: RDS   
Outputs:
  EndPoint: 
    Description: 'EndPoint for RDS DB'
    Value: !GetAtt 'RDSInstance.Endpoint.Address'
  InstanceName:
    Description:  'InstanceName of the newly created RDS Instance'
    Value: !Ref 'RDSInstance'        
