#This CF template will build RDS Databse for SPIDER Application from snapshot in AWS PREPROD, PROD and DR.
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  Environment:
    Type: String
    Description: Environment Name (PREPROD/PROD/DR)
    AllowedValues: ['PREPROD', 'PROD', 'DR', 'preprod', 'prod', 'dr']
  Database:
    Type: String
    Default: 'SPIDER'
   BuildNumber:
    Type: String  
  AppID:
    Type: String
    Default: '0ACC151C-439E-415A-9794-7C42C13A551D'
    Description: AppID
  BU:
    Type: String
    Default: 'DJI'
    Description: BU Name
  SupportGroup:
    Type: String
    Default: 'IM-SPDJI-Index infrastructure'
    Description: SupportGroup Name
  DBSnapshotIdentifier:
    Type: String
    Description:  ARN of the DB snapshot  
  AllowMajorVersionUpgrade:
    Description: If you update the EngineVersion property to a version that is different from the DB instances current major version, set this property to true
    Type: String
    AllowedValues: [true, false]
    ConstraintDescription: "Value must be boolean value."
    Default: false
  AutoMinorVersionUpgrade:  
    Description: Indicates that minor engine upgrades are applied automatically to the DB instance during the maintenance window. The default value is true.
    Type: String
    AllowedValues: [true, false]
    Default: false
    ConstraintDescription: "Value must be boolean value."  
  BackupRetentionPeriod:
    Description: The number of days during which automatic DB snapshots are retained.
    Type: String
    AllowedPattern: "^[0-9]{1,3}$"
    ConstraintDescription: "Value must be a valid number between 0-999."
    Default: 35
  DBCACertificateIdentifier:
    Description: The name of the CA Certificate to use with the DB instance.
    Type: String
    Default: rds-ca-rsa2048-g1
    AllowedValues: [rds-ca-rsa2048-g1,rds-ca-rsa4096-g1,rds-ca-ecc384-g1,rds-ca-2019]
  DBInstanceClass:
    Description: The name of the compute and memory capacity classes of the DB instance.
    Type: String
    Default: db.r5.xlarge
    AllowedValues: [db.r3.large,db.r3.xlarge,db.r5.xlarge,db.r5.2xlarge] 
  #DBName:
  #  Description: The name of the database inside the instance.
  #  Type: String
  #  Default: spiderd
  Engine:
    Description: The name of the database engine to be used for this instance.
    Type: String
    Default: aurora-mysql
    AllowedValues: [mysql, mariadb, postgres, oracle-ee,aurora-postgresql,aurora-mysql]
    ConstraintDescription: "Please specify either a mysql, mariadb, or postgres engine for the RDS instance."
  DeletionProtection:
    Description: A value that indicates whether the DB cluster has deletion protection enabled. The database can be deleted when deletion protection is enabled. By default, deletion protection is disabled.
    Type: String
    Default: yes
  EngineVersion:
    Description: The version number of the database engine to use.
    Type: String
    #Default: 5.7.mysql_aurora.2.10.0
  PreferredMaintenanceWindow:
    Description: Maintenance Window.
    Type: String
    Default: sat:04:01-sat:08:00
  PreferredBackupWindow:
    Description: Backup Window.
    Type: String
    Default: 03:00-04:00
  DBInstanceIdentifier1:
    Description: A name for the DB instance.
    Type: String
  DBInstanceIdentifier2:
    Description: A name for the DB instance.
    Type: String  
  DBClusterInstanceIdentifier:
    Description: A name for the DB cluster.
    Type: String
  DBGlobalClusterIdentifier:
    Description: A name for the DB cluster.
    Type: String  

Mappings:
  DBSubnetGroup:
    PREPROD:
      DBSubnetGroupName: preprod-priv-subnet-group
    PROD:
      DBSubnetGroupName: prod-priv-subnet-group
    DR:
      DBSubnetGroupName: dr1-db-subnet-group-01
  VPCSecurityGroups:
    PREPROD:
      SGID: [sg-0e5a7137dd4c093e1]
    PROD:
      SGID: [sg-9e7894ef]
    DR:
      SGID: [sg-0371be49396b87216]
  KeyNames:
    PREPROD:
      Name: 'alias/rds-prod-kms-key'
    PROD:
      Name: 'alias/rds-prod-kms-key'
    DR:
      Name: 'alias/rds-dr-oregon-key1'
  DBParameterGroupName:
    PREPROD: 
      Name: preprod-spider-param-auroramysql
    PROD:
      Name: prod-spider-param-auroramysql
    DR:
      Name: dr-spider-param-auroramysql
  DBOptionGroupName:
    PREPROD: 
      Name: default:aurora-mysql-5-7  ##preprod-spider-option-auroramysql
    PROD:
      Name: default:aurora-mysql-5-7  ##prod-spider-option-auroramysql
    DR:
      Name: default:aurora-mysql-5-7  ##dr-spider-option-auroramysql
  DBClusterParameterGroup:
    PREPROD:
      Name: preprod-spider-cluster-param-auroramysql
    PROD:
      Name:  prod-spider-cluster-param-auroramysql
    DR:
      Name: dr-spider-cluster-param-auroramysql
  DBName:
    PREPROD:
      Name: spiderspt
    PROD:
      Name: spiderp
    DR:
      Name: spiderp
  MultiAZ:
    PREPROD:
      Name: false
    PROD:
      Name: false
    DR:
      Name: false

Resources:
  SpiderGlobalCluster:
    Type: AWS::RDS::GlobalCluster
    Properties:
      DeletionProtection: !Ref DeletionProtection
      Engine: !Ref Engine
      EngineVersion: !Ref EngineVersion
      GlobalClusterIdentifier: !Ref DBGlobalClusterIdentifier
      StorageEncrypted: Yes
      
  SPIDERRDSCluster:
    Type: AWS::RDS::DBCluster
    DependsOn: SpiderGlobalCluster
    Properties:
      GlobalClusterIdentifier: !Ref SpiderGlobalCluster
      DBClusterIdentifier: !Ref DBClusterInstanceIdentifier
      Engine: !Ref Engine
      Port: 3306
      EngineVersion: !Ref EngineVersion
      SnapshotIdentifier: !Ref DBSnapshotIdentifier
      DBSubnetGroupName: !FindInMap
        - DBSubnetGroup
        - !Ref Environment
        - DBSubnetGroupName
      #MasterUsername: !Ref DBUsername
      #MasterUserPassword: !Ref DBPassword
      DBClusterParameterGroupName: !FindInMap
        - DBClusterParameterGroup
        - !Ref Environment
        - Name
      DeletionProtection: !Ref DeletionProtection
      VpcSecurityGroupIds: !FindInMap
        - VPCSecurityGroups
        - !Ref Environment
        - SGID
      BackupRetentionPeriod: !Ref BackupRetentionPeriod
      CopyTagsToSnapshot: Yes
      PreferredMaintenanceWindow: !Ref PreferredMaintenanceWindow
      PreferredBackupWindow: !Ref PreferredBackupWindow
      StorageEncrypted: Yes
      KmsKeyId: !FindInMap
        - KeyNames
        - !Ref Environment
        - Name
      #DatabaseName: !FindInMap
      #  - DBName
      #  - !Ref Environment
      #  - Name
      EnableCloudwatchLogsExports:
        - 'error'
        - 'slowquery'

      Tags:
      - Key: Name
        Value: !Sub ${Environment}-${DBClusterInstanceIdentifier}
      - Key: Owner
        Value: !Ref Database
      - Key: AppID
        Value: !Ref AppID
      - Key: BU
        Value: !Ref BU
      - Key: Environment
        Value: !Ref Environment
      - Key: SupportGroup
        Value: !Ref SupportGroup
      - Key: UsedFor
        Value: Aurora Cluster
      - Key: Build_Number
        Value: !Ref BuildNumber
      

  SPIDERRDSInstance1:
    Type: 'AWS::RDS::DBInstance'
    DependsOn: SPIDERRDSCluster
    Properties:
      DBClusterIdentifier: !Ref SPIDERRDSCluster
      DBInstanceClass: !Ref DBInstanceClass
      CACertificateIdentifier: !Ref DBCACertificateIdentifier
      #DBSnapshotIdentifier: !Ref DBSnapshotIdentifier
      PreferredMaintenanceWindow: !Ref PreferredMaintenanceWindow
      CopyTagsToSnapshot: Yes
      PubliclyAccessible: No
      DBInstanceIdentifier: !Ref DBInstanceIdentifier1
      DBParameterGroupName: !FindInMap
        - DBParameterGroupName
        - !Ref Environment
        - Name
      OptionGroupName: !FindInMap
        - DBOptionGroupName
        - !Ref Environment 
        - Name
      Engine: !Ref Engine
      EngineVersion: !Ref EngineVersion
      PubliclyAccessible: No

      Tags:
      - Key: Name
        Value: !Sub ${Environment}-${Database}-${DBInstanceIdentifier1}
      - Key: Owner
        Value: !Ref Database
      - Key: AppID
        Value: !Ref AppID
      - Key: BU
        Value: !Ref BU
      - Key: Environment
        Value: !Ref Environment
      - Key: SupportGroup
        Value: !Ref SupportGroup
      - Key: UsedFor
        Value: RDS

  SPIDERRDSInstance2:
    Type: 'AWS::RDS::DBInstance'
    DependsOn: SPIDERRDSCluster
    Properties: 
      DBClusterIdentifier: !Ref SPIDERRDSCluster
      DBInstanceClass: !Ref DBInstanceClass
      CACertificateIdentifier: !Ref DBCACertificateIdentifier
      #DBSnapshotIdentifier: !Ref DBSnapshotIdentifier
      PreferredMaintenanceWindow: !Ref PreferredMaintenanceWindow
      CopyTagsToSnapshot: Yes
      PubliclyAccessible: No
      DBInstanceIdentifier: !Ref DBInstanceIdentifier2
      DBParameterGroupName: !FindInMap
        - DBParameterGroupName
        - !Ref Environment
        - Name
      OptionGroupName: !FindInMap
        - DBOptionGroupName
        - !Ref Environment
        - Name
      Engine: !Ref Engine
      EngineVersion: !Ref EngineVersion
      PubliclyAccessible: No

      Tags:
      - Key: Name
        Value: !Sub ${Environment}-${Database}-${DBInstanceIdentifier2}
      - Key: Owner
        Value: !Ref Database
      - Key: AppID
        Value: !Ref AppID
      - Key: BU
        Value: !Ref BU
      - Key: Environment
        Value: !Ref Environment
      - Key: SupportGroup
        Value: !Ref SupportGroup
      - Key: UsedFor
        Value: RDS  
        
Outputs:
  GlobalClusterName:
    Description:  'InstanceName of the newly created RDS Instance'
    Value: !Ref 'SpiderGlobalCluster'
  ClusterEndpoint:
    Description: 'Aurora Cluster/Writer Endpoint'
    Value: !GetAtt 'SPIDERRDSCluster.Endpoint.Address'
  ReaderEndpoint:
    Description: 'Aurora Reader Endpoint'
    Value: !GetAtt 'SPIDERRDSCluster.ReadEndpoint.Address'
  ClusterName:
    Description:  'Cluster Name'
    Value: !Ref 'SPIDERRDSCluster'
