#This CF template will RDS for MDB Application in AWS higher environment. 
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  Environment:
    Type: String
    Description: Environment Name (PREPROD/PROD/DR)
    AllowedValues: ['PREPROD','PROD','DR', 'prod', 'dr','preprod']
  Database:
    Type: String
    Default: 'MDB'
    Description: Database Name
  BuildNumber:
    Type: String
  AppID:
    Type: String
    Default: '27932A31-F152-45C4-AB96-C933C978418B'
    Description: AppID
  BU:
    Type: String
    Default: 'DJI'
    Description: BU Name
  SupportGroup:
    Type: String
    Default: 'IM-SPDJI-Index infrastructure'
    Description: SupportGroup Name
  DBUsername:
    NoEcho: 'true'
    Description: RDS DB Master username
    Type: String
    Default: 'rdsmstr'
    MinLength: '3'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters
  DBPassword:
    NoEcho: 'true'
    Description: Password of RDS database access
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '^[a-zA-Z]+[0-9a-zA-Z_]*$'
    ConstraintDescription: Must start with a letter. Only numbers, letters, and _ accepted. max length 16 characters
  AllowMajorVersionUpgrade:
    Description: If you update the EngineVersion property to a version that is different from the DB instances current major version, set this property to true
    Type: String
    AllowedValues: [true, false]
    ConstraintDescription: "Value must be boolean value."
    Default: false
  AutoMinorVersionUpgrade:  
    Description: Indicates that minor engine upgrades are applied automatically to the DB instance during the maintenance window. The default value is true.
    Type: String
    AllowedValues: [true, false]
    Default: true
    ConstraintDescription: "Value must be boolean value."  
  BackupRetentionPeriod:
    Description: The number of days during which automatic DB snapshots are retained.
    Type: String
    AllowedPattern: "^[0-9]{1,3}$"
    ConstraintDescription: "Value must be a valid number between 0-999."
    Default: 35   ##was 3 before
  DBInstanceClass:
    Description: The name of the compute and memory capacity classes of the DB instance.
    Type: String
    Default: db.r5.2xlarge
    AllowedValues: [db.r5.large,db.r5.xlarge,db.r5.2xlarge] 
  Engine:
    Description: The name of the database engine to be used for this instance.
    Type: String
    Default: aurora-postgresql
    AllowedValues: [mysql, mariadb, postgres, oracle-ee,aurora-postgresql]
    ConstraintDescription: "Please specify either a mysql, mariadb, or postgres engine for the RDS instance."
  DeletionProtection:
    Description: A value that indicates whether the DB cluster has deletion protection enabled. The database can be deleted when deletion protection is enabled. By default, deletion protection is disabled.
    Type: String
    Default: yes
  EngineVersion:
    Description: The version number of the database engine to use.
    Type: String
    Default: 11.15
  DBCACertificateIdentifier:
    Description: The name of the CA Certificate to use with the DB instance.
    Type: String
    Default: rds-ca-rsa2048-g1
    AllowedValues: [rds-ca-rsa2048-g1,rds-ca-rsa4096-g1,rds-ca-ecc384-g1,rds-ca-2019]
  PreferredMaintenanceWindow:
    Description: Maintenance Window.
    Type: String
    #Default: fri:03:00-fri:04:00
    Default: sat:04:01-sat:08:00
    
  PreferredBackupWindow:
    Description: Backup Window.
    Type: String
    #Default: fri:03:00-fri:04:00
    Default: 03:01-04:00  
    
  DBGlobalClusterIdentifier:
    Description: A name for the DB cluster.
    Type: String  
  DBClusterIdentifier:
    Description: A name for the DB cluster.
    Type: String
  DBInstanceIdentifier1:
    Description: A name for the DB instance.
    Type: String
  DBInstanceIdentifier2:
    Description: A name for the DB instance.
    Type: String 
  PerformanceInsightsRetentionPeriod:
    Type: String
    Default: 7
    AllowedValues: [7,35]


Mappings:
  DBSubnetGroup:
    PREPROD:
      DBSubnetGroupName: preprod-use1-priv-subnet-group
    PROD:
      DBSubnetGroupName: prod-use1-priv-rds-subnet-group-01
    DR:
      DBSubnetGroupName: dr-usw2-priv-rds-subnet-group-01
  VPCSecurityGroups:
    PREPROD:
      SGID: [sg-0e5a7137dd4c093e1]
    PROD:
      SGID: [sg-9e7894ef]
    DR:
      SGID: [sg-0371be49396b87216]
  KeyNames:
    PREPROD:
      Name: 'alias/rds-prod-kms-key'
    PROD:
      Name: 'alias/rds-prod-kms-key' 
    DR:
      Name: 'alias/rds-dr-oregon-key1' 
  DBParameterGroupName:
    PREPROD:
      Name: preprod-mdb-param-aurapostgres
    PROD: 
      Name: prod-mdb-param-aurapostgres
    DR:
      Name: dr-mdb-param-aurapostgres
  DBClusterParameterGroup:
    PREPROD:
      Name: preprod-mdb-cluster-param-aurapostgres
    PROD:
      Name: prod-mdb-cluster-param-aurapostgres
    DR:
      Name: dr-mdb-cluster-param-aurapostgres 
  DBName:
    PREPROD:
      Name: mdbspt
      #Name: MDBSPT
    PROD:
      Name: mdbp
      #Name: MDBP
    DR:
      Name: mdbp_dr
      #Name: MDBP_DR

Resources:
  MDBGlobalCluster:
    Type: AWS::RDS::GlobalCluster
    Properties: 
      DeletionProtection: !Ref DeletionProtection
      Engine: !Ref Engine
      EngineVersion: !Ref EngineVersion
      GlobalClusterIdentifier: !Ref DBGlobalClusterIdentifier
      StorageEncrypted: Yes

  MDBRDSCluster1:
    Type: AWS::RDS::DBCluster
    DependsOn: MDBGlobalCluster
    Properties:
      GlobalClusterIdentifier: !Ref MDBGlobalCluster
      DBClusterIdentifier: !Ref DBClusterIdentifier
      Engine: !Ref Engine
      EngineVersion: !Ref EngineVersion
      Port: 5432
      DBSubnetGroupName: !FindInMap
        - DBSubnetGroup
        - !Ref Environment
        - DBSubnetGroupName
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DatabaseName: !FindInMap
        - DBName
        - !Ref Environment
        - Name
      DBClusterParameterGroupName: !FindInMap
        - DBClusterParameterGroup
        - !Ref Environment
        - Name
      DeletionProtection: !Ref DeletionProtection
      VpcSecurityGroupIds: !FindInMap
        - VPCSecurityGroups
        - !Ref Environment
        - SGID
      StorageEncrypted: Yes
      KmsKeyId: !FindInMap
        - KeyNames
        - !Ref Environment
        - Name
      BackupRetentionPeriod: !Ref BackupRetentionPeriod
      EnableIAMDatabaseAuthentication: Yes
      #CopyTagsToSnapshot: Yes
      EnableCloudwatchLogsExports: 
        - 'postgresql'
      Tags:
      - Key: Name
        Value: !Sub ${Environment}-${DBClusterIdentifier}
      - Key: Owner
        Value: !Ref Database
      - Key: AppID
        Value: !Ref AppID
      - Key: BU
        Value: !Ref BU
      - Key: Environment
        Value: !Ref Environment
      - Key: SupportGroup
        Value: !Ref SupportGroup
      - Key: UsedFor
        Value: Aurora Cluster
      - Key: Build_Number
        Value: !Ref BuildNumber

  MDBRDSInstance1: 
    Type: 'AWS::RDS::DBInstance'
    DependsOn: MDBRDSCluster1
    Properties: 
      DBClusterIdentifier: !Ref MDBRDSCluster1
      DBInstanceClass: !Ref DBInstanceClass
      PreferredMaintenanceWindow: !Ref PreferredMaintenanceWindow
      PreferredBackupWindow: !Ref PreferredBackupWindow
      CACertificateIdentifier: !Ref DBCACertificateIdentifier
      CopyTagsToSnapshot: Yes
      DeleteAutomatedBackups: Yes
      PubliclyAccessible: No
      DBInstanceIdentifier: !Ref DBInstanceIdentifier1
      DBParameterGroupName: !FindInMap
        - DBParameterGroupName
        - !Ref Environment
        - Name
      Engine: !Ref Engine
      EngineVersion: !Ref EngineVersion
      PubliclyAccessible: No
      EnablePerformanceInsights: Yes
      PerformanceInsightsKMSKeyId: arn:aws:kms:us-east-1:897860998156:key/8c63c41b-8265-47cb-ad5d-7fbd9116a2f4
      PerformanceInsightsRetentionPeriod: !Ref PerformanceInsightsRetentionPeriod

      Tags:
      - Key: Name
        Value: !Sub ${Environment}-${Database}-${DBInstanceIdentifier1}
      - Key: Owner
        Value: !Ref Database
      - Key: AppID
        Value: !Ref AppID
      - Key: BU
        Value: !Ref BU
      - Key: Environment
        Value: !Ref Environment
      - Key: SupportGroup
        Value: !Ref SupportGroup
      - Key: UsedFor
        Value: RDS
      - Key: AutomatedSnapshot
        Value: Yes

  MDBRDSInstance2: 
    Type: 'AWS::RDS::DBInstance'
    DependsOn: MDBRDSCluster1
    Properties: 
      DBClusterIdentifier: !Ref MDBRDSCluster1
      DBInstanceClass: !Ref DBInstanceClass
      PreferredMaintenanceWindow: !Ref PreferredMaintenanceWindow
      CACertificateIdentifier: !Ref DBCACertificateIdentifier
      CopyTagsToSnapshot: Yes
      DeleteAutomatedBackups: Yes
      PubliclyAccessible: No
      DBInstanceIdentifier: !Ref DBInstanceIdentifier2
      DBParameterGroupName: !FindInMap
        - DBParameterGroupName
        - !Ref Environment
        - Name
      Engine: !Ref Engine
      EngineVersion: !Ref EngineVersion
      PubliclyAccessible: No
      EnablePerformanceInsights: Yes
      PerformanceInsightsKMSKeyId: arn:aws:kms:us-east-1:897860998156:key/8c63c41b-8265-47cb-ad5d-7fbd9116a2f4
      PerformanceInsightsRetentionPeriod: !Ref PerformanceInsightsRetentionPeriod
      

      Tags:
      - Key: Name
        Value: !Sub ${Environment}-${Database}-${DBInstanceIdentifier2}
      - Key: Owner
        Value: !Ref Database
      - Key: AppID
        Value: !Ref AppID
      - Key: BU
        Value: !Ref BU
      - Key: Environment
        Value: !Ref Environment
      - Key: SupportGroup
        Value: !Ref SupportGroup
      - Key: UsedFor
        Value: RDS
      - Key: AutomatedSnapshot
        Value: Yes      



Outputs:
  GlobalClusterName:
    Description:  'InstanceName of the newly created RDS Instance'
    Value: !Ref 'MDBGlobalCluster'
  ClusterEndpoint:
    Description: 'Aurora Cluster/Writer Endpoint'
    Value: !GetAtt 'MDBRDSCluster1.Endpoint.Address'
  ReaderEndpoint:
    Description: 'Aurora Reader Endpoint'
    Value: !GetAtt 'MDBRDSCluster1.ReadEndpoint.Address'       


  
