#This CFT will deploy RDS DB for EDM in AWS lower environment. 
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  Environment:
    Type: String
    Description: Environment Name (PREPROD/PROD)
    AllowedValues: ['PREPROD', 'PROD', 'preprod', 'prod']
  BuildNumber:
    Type: String
    Description: Build Number of Jenkins
  Database:
    Type: String
    Default: 'EDM'
    Description: Database Name  
  AppID:
    Type: String
    Default: 'CCBE9072-1B6A-5910-B29F-A756624BCBC9' 
    Description: AppID
  BU: 
    Type: String
    Default: 'DJI'
    Description: BU Name 
  SupportGroup:
    Type: String
    Default: 'IM-SPDJI-Index infrastructure'
    Description: SupportGroup Name
  #DBUsername:
    #NoEcho: 'true'
    #Description: Username for MySQL database access
    #Type: String
    #Default: 'rdsmstr'
    #MinLength: '1'
    #MaxLength: '16'
    #AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    #ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  #DBPassword:
    #NoEcho: 'true'
    #Description: Password MSSQL database access
    #Type: String
    #MinLength: '8'
    #MaxLength: '41'
    #AllowedPattern: '^[a-zA-Z]+[0-9a-zA-Z_]*$'
    #ConstraintDescription: Must start with a letter. Only numbers, letters, and _ accepted. max length 16 characters 
  AllowMajorVersionUpgrade:
    Description: If you update the EngineVersion property to a version that is different from the DB instances current major version, set this property to true.
    Type: String
    AllowedValues: [true, false]
    ConstraintDescription: "Value must be boolean value."
    Default: false
  AutoMinorVersionUpgrade:
    Description: Indicates that minor engine upgrades are applied automatically to the DB instance during the maintenance window. The default value is true.
    Type: String
    AllowedValues: [true, false]
    Default: true
    ConstraintDescription: "Value must be boolean value."
  BackupRetentionPeriod:
   Description: The number of days during which automatic DB snapshots are retained.
   Type: String
   AllowedPattern: "^[0-9]{1,3}$"
   ConstraintDescription: "Value must be a valid number between 0-999."
   Default: 35
  DBInstanceClass:
    Description: The name of the compute and memory capacity classes of the DB instance.
    Type: String
    Default: db.m4.2xlarge
    AllowedValues: [db.m4.2xlarge,db.m5.4xlarge,db.m5.8xlarge,db.m5.12xlarge,db.m5.16xlarge,db.m5.24xlarge,db.r5.2xlarge]   
  Engine:
    Description: The name of the database engine to be used for this instance.
    Type: String
    Default: sqlserver-ee
    AllowedValues: [sqlserver-se,mysql, mariadb, postgres,oracle-ee,sqlserver-ee]
    ConstraintDescription: "Please specify either a mysql, mariadb, or postgres engine for the RDS instance."
  MultiAZ:
    Description: Specifies if the database instance is a multiple Availability Zone deployment.
    Type: String
    AllowedValues: [true, false]
    Default: false
    ConstraintDescription: "Value must be boolean value."  
  DeletionProtection:
    Description: A value that indicates whether the DB cluster has deletion protection enabled. The database can be deleted when deletion protection is enabled. By default, deletion protection is disabled.
    Type: String
    Default: yes
  PreferredBackupWindow:
    Description: Backup Window.
    Type: String
    Default: 03:01-04:00
  EngineVersion:
    Description: The version number of the database engine to use.
    Type: String
    #Default: 15.00.4198.2.v1
    AllowedValues: [15.00.4236.7.v1,15.00.4198.2.v1,8.0.21,8.0.20,8.0.19,8.0.23,8.0.29,8.0.28]
  DBInstanceIdentifier:
    Description: A name for the DB instance.
    Type: String
  StorageType:
    Type: String
    Default: gp3
    AllowedValues: [gp3,gp2, io1]
  MaxAllocatedStorage:
    Type: String
    Default: 1000
    Description: The upper limit to which Amazon RDS can automatically scale the storage of the DB instance.  
  PerformanceInsightsRetentionPeriod:
    Type: String
    Default: 7
    AllowedValues: [7,35]
  DBCACertificateIdentifier:
    Description: The name of the CA Certificate to use with the DB instance.
    Type: String
    Default: rds-ca-rsa2048-g1
    AllowedValues: [rds-ca-rsa2048-g1,rds-ca-rsa4096-g1,rds-ca-ecc384-g1,rds-ca-2019]
  DBSnapshotIdentifier:
    Type: String
    Description:  ARN of the DB snapshot

Mappings:
  DBSubnetGroup:
    PREPROD:
      DBSubnetGroupName: preprod-use1-priv-subnet-group
    PROD:
      DBSubnetGroupName: prod-use1-priv-rds-subnet-group-01
  VPCSecurityGroups:
    PREPROD:
      SGID: [sg-0e5a7137dd4c093e1]
    PROD:
      SGID: [sg-9e7894ef]
  KeyNames:
    PREPROD:
      Name: 'alias/rds-prod-kms-key' 
    PROD:
      Name: 'alias/rds-prod-kms-key'
  DBParameterGroupName:
    PROD: 
      Name: prod-use1-edm-param-mssql
    PREPROD:
      Name: preprod-use1-edm-param-mssql
  OptionGroupName:
    PROD:
      Name: prod-use1-edm-option-mssql
    PREPROD:
      Name: preprod-use1-edm-option-mssql
  DBAllocatedStorage:
    PREPROD:
      Storage: 2048
    PROD:
      Storage: 2048
  MaxAllocatedStorage:
    PREPROD:
      storage: 3072
    PROD:
      storage: 3072
  DBName:
    PREPROD:
      Name: edmspt
    PROD:
      Name: edmp
  DBInstanceClass:
    PREPROD:
      instancetype: db.m5.8xlarge
    PROD:
      instancetype: db.m5.8xlarge
  PreferredMaintenanceWindow:
    PREPROD: 
      window: sat:04:01-sat:08:00
    PROD:
      window: sat:04:01-sat:08:00
   
Resources:
  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: !FindInMap
        - DBAllocatedStorage
        - !Ref Environment
        - Storage
      AllowMajorVersionUpgrade: !Ref AllowMajorVersionUpgrade
      AutoMinorVersionUpgrade: !Ref AutoMinorVersionUpgrade
      BackupRetentionPeriod: !Ref BackupRetentionPeriod
      LicenseModel: license-included
      DBInstanceClass: !FindInMap 
        - DBInstanceClass
        - !Ref Environment
        - instancetype
      #DBName: !FindInMap
      #  - DBName
      #  - !Ref Environment
      #  - Name
      Engine: !Ref Engine
      EngineVersion: !Ref EngineVersion
      DBSubnetGroupName: !FindInMap
        - DBSubnetGroup
        - !Ref Environment
        - DBSubnetGroupName
      VPCSecurityGroups: !FindInMap
        - VPCSecurityGroups
        - !Ref Environment
        - SGID
      #MasterUsername: !Ref DBUsername
      #MasterUserPassword: !Ref DBPassword
      PreferredMaintenanceWindow: !FindInMap
        - PreferredMaintenanceWindow
        - !Ref Environment
        - window
      PreferredBackupWindow: !Ref PreferredBackupWindow
      MultiAZ: !Ref MultiAZ
      Port: '1433'
      StorageEncrypted: Yes
      DeletionProtection: !Ref DeletionProtection
      CopyTagsToSnapshot: Yes
      DeleteAutomatedBackups: Yes
      PubliclyAccessible: No
      StorageType: !Ref StorageType
      DBInstanceIdentifier: !Ref DBInstanceIdentifier
      EnablePerformanceInsights: Yes
      PerformanceInsightsKMSKeyId: arn:aws:kms:us-east-1:897860998156:key/8c63c41b-8265-47cb-ad5d-7fbd9116a2f4
      #PerformanceInsightsRetentionPeriod: !Ref PerformanceInsightsRetentionPeriod
      MonitoringInterval: 60
      MonitoringRoleArn: 'arn:aws:iam::897860998156:role/rds-monitoring-role'
      CACertificateIdentifier: !Ref DBCACertificateIdentifier
      DBSnapshotIdentifier: !Ref DBSnapshotIdentifier
      KmsKeyId: !FindInMap
        - KeyNames
        - !Ref Environment
        - Name
      DBParameterGroupName: !FindInMap
        - DBParameterGroupName
        - !Ref Environment
        - Name
      OptionGroupName: !FindInMap
        - OptionGroupName
        - !Ref Environment
        - Name
      MaxAllocatedStorage: !FindInMap
        - MaxAllocatedStorage
        - !Ref Environment
        - storage
      EnableCloudwatchLogsExports:
        - 'agent'
        - 'error'  
      Tags:
      - Key: Name
        Value: !Sub ${Environment}-${Database}-${DBInstanceIdentifier}-${BuildNumber}
      - Key: Owner
        Value: !Ref Database
      - Key: AppID
        Value: !Ref AppID
      - Key: BU
        Value: !Ref BU
      - Key: Environment
        Value: !Ref Environment
      - Key: SupportGroup
        Value: !Ref SupportGroup
      - Key: UsedFor
        Value: RDS   
      - Key: AutomatedSnapshot
        Value: Yes
      - Key: Build_Number
        Value: !Ref BuildNumber
Outputs:
  EndPoint: 
    Description: 'EndPoint for RDS DB'
    Value: !GetAtt 'RDSInstance.Endpoint.Address'
  InstanceName:
    Description:  'InstanceName of the newly created RDS Instance'
    Value: !Ref 'RDSInstance'        
