---
  - name: Reboot after Patching
    hosts: all
    gather_facts: yes
    become: yes
    become_user: root
    ignore_unreachable: yes
      
    tasks:
#      - name: check if server reboot is required
#        shell: needs-restarting -r | grep -i "Reboot is required"
#        register: restart_status
#        ignore_errors: yes

      - name: Restart server for installed updates to take effect
        command: /sbin/shutdown -r +1
        async: 1
        poll: 0
        become: yes
        become_user: root
        ignore_errors: yes
#        when: "'Reboot is required' in restart_status.stdout"
#        failed_when: "'FAILED' in restart_status.stderr"

      - name: Sleep for a min
        pause:
          minutes: 1

      - name: Wait for the reboot and reconnect
        local_action: wait_for host="{{ inventory_hostname }}" search_regex=OpenSSH port=22 timeout=600
        ignore_errors: yes

      - name: Wait for SSH to come up
        wait_for_connection:
          delay: 60
          timeout: 30
        ignore_errors: true

#      - name: Sleep for a min
#        pause:
#          minutes: 1

      - name: Check the Uptime of the servers
        shell: "uptime"
        ignore_unreachable: yes
