---
      - name: Wait for Primary Cluster to Available
        shell: "/usr/local/bin/aws rds wait --region {{ SOURCE_REGION }} db-instance-available --db-instance-identifier {{ PRIMARY_INSTANCE.msg }}"
        register: wait_for_available

      - name: Debug wait for available
        debug:
          msg: "{{ wait_for_available }}"

      - name: Get the DB Instance Status
        shell: "/usr/local/bin/aws rds describe-db-instances --region {{ SOURCE_REGION }} --db-instance-identifier {{ PRIMARY_INSTANCE.msg }} --query DBInstances[].DBInstanceStatus --output text"
        register: primary_status
        until: replica_status.stdout != 'upgrading'
        retries: 60
        delay: 10        
        when: wait_for_available.rc == 0
        ignore_errors: yes

      - name: Debug DB Instance Status
        debug:
          msg: "{{ primary_status.stdout }}"

      - name: Get the Engine Version of the instance
        shell: "/usr/local/bin/aws rds describe-db-instances --region {{ SOURCE_REGION }} --db-instance-identifier {{ PRIMARY_INSTANCE.msg }} --query DBInstances[].EngineVersion --output text"
        register: primary_engine_version
        ignore_errors: yes
        #when: primary_status.stdout == "available"
        failed_when: "'FAILED' in primary_status.stderr"

      - name: Engine Version Result
        debug:
          msg: "{{ primary_engine_version.stdout }}"

      - set_fact:
          ENGINE_VERSION: "{{ primary_engine_version.stdout }}"

      - name: Print Result of Primary Instance Patching
        debug:
          msg: "Patching has been completed for Primary Instance with the version {{ AVAILABLE_VERSION }}"
        when: AVAILABLE_VERSION  == ENGINE_VERSION

      - name: Print Results of Primary Instance Patching
        debug:
          msg: "Patching is unsuccesfull for Primary Instance as {{ AVAILABLE_VERSION }} is not matched with {{ ENGINE_VERSION }}"
        when: AVAILABLE_VERSION != ENGINE_VERSION

      - mail:
          from: IndexInfraMBX@spglobal.com
          #to: kirubakaran.kannan@spglobal.com
          to: 'InfraNotificationMBX@spglobal.com,IndexInfraMBX@spglobal.com'
          subject: 'SPDJI AWS RDS PATCHING JOB UPDATE:  For {{ CLUSTER_NAME }} in {{ JOB_NAME }} Build Number {{ BUILD_NUMBER }}'
          body: 'Minor Version Upgrade is completed for primary Instance {{ CLUSTER_NAME }} Instance with {{ AVAILABLE_VERSION }} Engine Version. For more details, Check console output at {{ BUILD_URL }}'
        when:
          - UPGRADE_TYPE == 'MinorVersion'
          - AVAILABLE_VERSION == ENGINE_VERSION

      - mail:
          from: IndexInfraMBX@spglobal.com
          #to: kirubakaran.kannan@spglobal.com
          to: 'InfraNotificationMBX@spglobal.com,IndexInfraMBX@spglobal.com'
          subject: 'SPDJI AWS RDS PATCHING JOB UPDATE:  For {{ CLUSTER_NAME }} in {{ JOB_NAME }} Build Number {{ BUILD_NUMBER }}'
          body: 'Minor Version Upgrade is unsuccessfull for primary Instance {{ CLUSTER_NAME }} Instance with {{ AVAILABLE_VERSION }} is not matched with {{ ENGINE_VERSION }} Engine Version. For more details, Check console output at {{ BUILD_URL }}'
        when:
          - UPGRADE_TYPE == 'MinorVersion'
          - AVAILABLE_VERSION != ENGINE_VERSION
